/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

// 7. Filtering via properties
extra["isFish"] = false

// 9. Add task only to spacific projects and execute it from toplevel

tasks.register("distanceToIceberg") {
    doFirst {
        println("20 nautical miles")
    }
}