/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

extra["producerMessage"] = null

// 1. Run without any dependencies defined
// ./gradlew -q action
// -> consumer gets null, since it executes as first; executiong tasks in alphanumeric order

// 2. Add dependencies - see consumer build script