/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/5.4.1/userguide/multi_project_builds.html
 */

rootProject.name = "gradle-workshop"

println("Gradle Workshop: settings.gradle.kts : This is also initialization phase!")

// Script Object: https://docs.gradle.org/current/dsl/org.gradle.api.Script.html
logger.lifecycle("Current dir: ${file(".").path}")

fileTree(".") {
    files.filter { it.path.contains("build") }.forEach { file ->
        logger.lifecycle(file.path)
    }
}

mkdir(".aem")
mkdir(".gap")

delete(".aem", ".gap")

// Settings Object: https://docs.gradle.org/current/dsl/org.gradle.api.Script.html

println("Root dir: $rootDir")
println("Settings: $settingsDir")

// plus configuration of projects which we will cover in multiproject builds: include(projectPaths), etc.
//file('subprojects').eachDir { dir ->
//    include dir.name
//            project(":${dir.name}").projectDir = dir
//}

val property: String by settings
println("Property value: $property")