/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

// 1. Let's setup build that will compile and run our Java application:
// dependencies: org.apache.commons:commons-math3:3.6.1
// our program main class: workshop.Main