/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

// 1. Configuring current project - based on build script location
tasks.register("hello") { doLast { println("Welcome to The Water project") } }

// 2. Configuring all projects at once
allprojects {
    // findByName finds task for thew water project
    // and when we are in a subproject we need to register the hello task since it is not yet present there
    tasks.findByName("hello") ?: tasks.register("hello") {
        doLast {
            println("I'm ${this.project.name}")
        }
    }
}

// 3. Configuring sub-projects only
subprojects {
    tasks.named("hello") {
        doLast {
            println("- I depend on water")
        }
    }
}

// 4. Configuring specific projects
project(":bluewhale") {
    tasks.named("hello") {
        doLast {
            println("- I'm the largest animal that has ever lived on this planet.")
        }
    }
}

// 5. Specific behaviour placed in projects script - see project krill

// 6. Dynamic configuration via filtering

configure(subprojects.filter { it.name != "tropicalFish" }) {
    tasks.named("hello") {
        doLast {
            println("- I love to spend time in the arctic waters.")
        }
    }
}

// 7. Filtering via properties - configuration dependencies

subprojects {
    val hello by tasks.existing

    afterEvaluate {
        if(extra["isFish"] as Boolean) {
            hello {
                doLast {
                    println("- I'm a fish")
                }
            }
        }
    }
}

// 8. Let's switch to the bluewhale project dir and execite from there. What is your guess?

// ../gradlew -q hello
//Gradle always eveluates all projects of a multi-project build and only then filters tasks by parameters and current dir.

// 9. Add task only to spacific projects and execute it from toplevel
// go to bluewhale and krill projects

// 10. Execute tasks by their absolute path

// cd tropicalFish ; ../gradlew -q :hello :krill:hello hello