/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

println("Hello World!")

System.out.println("Using Java Libs")

// muttablity

val immuttable = "immutable value" // immutable = "new value" - won't compile
var muttable = "muttable"
muttable = "new value"
println("Printing values: $immuttable, $muttable")

// nullable types

val nullableString: String? = null
println("Printing nullable type: ${nullableString ?: "default value"}")

// Functions and return statement
fun sayHelloWorld() {
    println("Function Hello World")
}

sayHelloWorld()

fun createMessage() { // in functions we need to return result explicitly
    "Last expression is returned from a function"
}

println(createMessage()) //kotlin.Unit

val createMessageLmbda =  { // last expression in lambda is returned
    "Last expression is returned from a function"
}

println(createMessageLmbda()) // Last expression is returned from a function

// Objects
class AEM(val company: String, val version: String) { // final by default
}

val aem = AEM("Adobe", "6.5") // new keyword omitted

println("AEM ${aem.version} made by ${aem.company}")

// Lambdas - advanced

val echoIt: (Any) -> Unit = { // need to specify type explicitly since it cannot be inferred otherwise
    println("Echoing it: $it")
}
echoIt(true) 
