/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

// Configuration vs execution: ./gradlew tasks

tasks.register("hello") {
    doFirst {
        logger.lifecycle("Heavy lifting!")
        Thread.sleep(5000)
    }
    logger.lifecycle("Lite task configuration!")
}

logger.lifecycle("Lite project configuration!")






